package com.example.recyclerviewlistountries

object CntryRes {
    val imgList = listOf(
        R.drawable.ru,
        R.drawable.cy,
        R.drawable.cz,
        R.drawable.ec,
        R.drawable.ee,
        R.drawable.eg,
        R.drawable.eh,
        R.drawable.er,
        R.drawable.fj,
        R.drawable.fk,
        R.drawable.gh,
        R.drawable.gi,
        R.drawable.gl,
        R.drawable.gy,
        R.drawable.hn,
        R.drawable.ie,
        R.drawable.il,
        R.drawable.io,
        R.drawable.ir,
        R.drawable.jp,
        R.drawable.kz,
        R.drawable.la,
        R.drawable.ly,
        R.drawable.md,
        R.drawable.mf,
        R.drawable.ml,
        R.drawable.mn,
        R.drawable.my,
        R.drawable.na,
        R.drawable.ae,
    )

    val nameList = listOf(
        "Россия",
        "Кипр",
        "Чехия",
        "Эквадор",
        "Эстония",
        "Египет",
        "Западная Сахара",
        "Эритрея",
        "Фиджи",
        "Фолклендские острова",
        "Гана",
        "Гибралтар",
        "Гренландия",
        "Гайана",
        "Гондурас",
        "Ирландия",
        "Израиль",
        "Британская территория в Индийском океане",
        "Иран",
        "Япония",
        "Казахстан",
        "Лаос",
        "Ливия",
        "Молдова",
        "Сен-Мартен",
        "Мали",
        "Монголия",
        "Малайзия",
        "Намибия",
        "Объединенные Арабские Эмираты",

    )
}